# Generated by Django 4.2.7 on 2023-12-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_status_selectedadvertisements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedAdvertisements',
        ),
    ]
